theme: jekyll-theme-midnight
# deployment
host: 0.0.0.0
port: 8080
title: Portfolio
baseurl: ""
repository: "rhildred/netlify-jekyll-github-pages"
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "admin/**"
    values:
      sitemap:         false
